# Generated by Django 4.2.4 on 2023-12-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=399),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='information',
            name='category',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='information',
            name='description',
            field=models.CharField(blank=True, max_length=399),
        ),
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='info'),
        ),
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
