# Generated by Django 4.2.4 on 2024-01-01 16:10

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_slide_alter_gallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=399)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slide')),
                ('notif_file', models.FileField(upload_to='notif_file')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
        ),
    ]
