# Generated by Django 4.2.4 on 2024-01-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_infosite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=399)),
                ('description1', models.CharField(blank=True, max_length=399)),
                ('name2', models.CharField(blank=True, max_length=399)),
                ('description2', models.CharField(blank=True, max_length=399)),
                ('name3', models.CharField(blank=True, max_length=399)),
                ('description3', models.CharField(blank=True, max_length=399)),
                ('name4', models.CharField(blank=True, max_length=399)),
                ('description4', models.CharField(blank=True, max_length=399)),
                ('name5', models.CharField(blank=True, max_length=399)),
                ('description5', models.CharField(blank=True, max_length=399)),
            ],
        ),
    ]
